### ISSUE TITLE
pnpm run dev, pnpm run dev:demo not working

### ISSUE THREAD

**Issue by kid-icarus** [automerge/automerge-repo#329]
Node versions: 18.15.0, 20.11.0
Pnpm version: 8.11.0

On a fresh clone, running

- `pnpm install`
- `pnpm build`
- `pnpm dev:demo`

I'm receiving the following build error:

```
automerge-repo on  main via  v20.11.0 took 7s
❯ pnpm run dev:demo

> @automerge/automerge-repo-monorepo@1.1.4 dev:demo /Users/ryank/Projects/scratch/automerge-repo
> pnpm -F @automerge/automerge-repo-demo-todo dev


> @automerge/automerge-repo-demo-todo@1.1.4 dev /Users/ryank/Projects/scratch/automerge-repo/examples/react-todo
> vite --open


  VITE v5.0.12  ready in 487 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
4:36:34 PM [vite] Pre-transform error: Failed to resolve import "@automerge/automerge-wasm" from "node_modules/.vite/deps/chunk-C5VS73WC.js?v=d18c2588". Does the file exist?
4:36:34 PM [vite] Pre-transform error: Failed to resolve import "@automerge/automerge-wasm" from "node_modules/.vite/deps/chunk-C5VS73WC.js?v=d18c2588". Does the file exist? (x2)
4:36:34 PM [vite] Internal server error: Failed to resolve import "@automerge/automerge-wasm" from "node_modules/.vite/deps/chunk-C5VS73WC.js?v=d18c2588". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/ryank/Projects/scratch/automerge-repo/examples/react-todo/node_modules/.vite/deps/chunk-C5VS73WC.js?v=d18c2588:1289:24
  1287|
  1288|  // ../../node_modules/.pnpm/@automerge+automerge@2.1.9/node_modules/@automerge/automerge/dist/mjs/stable.js
  1289|  import * as wasm from "@automerge/automerge-wasm";
     |                         ^
  1290|  var __rest = function(s, e) {
  1291|    var t = {};
      at formatError (file:///Users/ryank/Projects/scratch/automerge-repo/node_modules/.pnpm/vite@5.0.12_@types+node@20.11.16/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:63768:46)
      at TransformContext.error (file:///Users/ryank/Projects/scratch/automerge-repo/node_modules/.pnpm/vite@5.0.12_@types+node@20.11.16/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:63762:19)
      at normalizeUrl (file:///Users/ryank/Projects/scratch/automerge-repo/node_modules/.pnpm/vite@5.0.12_@types+node@20.11.16/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:62037:33)
      at async file:///Users/ryank/Projects/scratch/automerge-repo/node_modules/.pnpm/vite@5.0.12_@types+node@20.11.16/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:62191:47
      at async Promise.all (index 2)
      at async TransformContext.transform (file:///Users/ryank/Projects/scratch/automerge-repo/node_modules/.pnpm/vite@5.0.12_@types+node@20.11.16/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:62112:13)
      at async Object.transform (file:///Users/ryank/Projects/scratch/automerge-repo/node_modules/.pnpm/vite@5.0.12_@types+node@20.11.16/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:64063:30)
      at async loadAndTransform (file:///Users/ryank/Projects/scratch/automerge-repo/node_modules/.pnpm/vite@5.0.12_@types+node@20.11.16/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:49741:29)
      at async viteTransformMiddleware (file:///Users/ryank/Projects/scratch/automerge-repo/node_modules/.pnpm/vite@5.0.12_@types+node@20.11.16/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:59342:32)
```

I can try to look at this later but thought I'd file an issue first, thanks folks 🙏🏻

**Comment by acurrieclark** [comment]
There is a PR (#322) in the works to get this fixed up. TLDR: we are using an outdated vite setup

**Comment by kid-icarus** [comment]
Ah, nice! Thanks @acurrieclark 🙏🏻

**Comment by pvh** [comment]
Should be all better now :)
